import {ConditionCodes} from '../../../../../const/gameData';

export type InputData = {
  atkInGame: number,
  atkConditionalPct: number,
  atkBuffPct: number,
  buffCount: number,
  buffZoneSelf: number,
  buffZoneAlly: number,
  exBlade: boolean,
  exWand: boolean,
  criticalRatePct: number,
  criticalDamagePct: number,
  criticalInspired: boolean,
  skillBuffPct: number,
  skillPassivePct: number,
  skillEnergized: boolean,
  punishersBkPct: number,
  punishersOtherPct: number,
  otherElemBonusPct: number,
  otherCurrentHpPct: number,
  targetElemCondCode: number,
  targetAfflictionCodes: Array<number>,
  targetDefBase: number,
  targetDefDownPct: number,
  targetDefBkRate: number,
  targetStateCode: ConditionCodes.NONE | ConditionCodes.TARGET_STATE_BK | ConditionCodes.TARGET_STATE_OD,
  filterElementCode: Array<number>,
  filterAfflictionCondCode: Array<number>,
  filterSharedOnly: boolean,
}
