---
engines:
  duplication:
    exclude_paths:
      # Test files
      - "**.test.ts"
      # Test data
      - "test/data/**"
exclude_paths:
  # Official New Relic EUM js
  - "public/js/newRelicEum.js"
